stages:
  - build

build_frontend:
  stage: build
  image: node:20-bookworm-slim
  cache:
    key:
      files:
        - frontend/package.json
        - frontend/package-lock.json
    paths:
      - frontend/node_modules/
  before_script:
    - cd frontend
    - npm ci --no-audit --no-fund
  script:
    - npm run build
