stages:
  - build

build_frontend:
  stage: build
  image: node:20.19-bookworm-slim
  cache:
    key:
      files:
        - frontend/package.json
        - frontend/package-lock.json
    paths:
      - frontend/.npm/
  before_script:
    - cd frontend
    - npm ci --cache .npm --no-audit --no-fund
  script:
    - npm run build
